apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: example03
  generateName: cleanup-after-sync-
  labels:
    codefresh.io/cert: cleanup-job
  #annotations:
      #argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
